const dummy = {
  "2021 JPY, purchaser price": "2021 JPY, purchaser price",
  "2021 SGD, purchaser price": "2021 SGD, purchaser price",
  "2021 THB, purchaser price": "2021 THB, purchaser price",
  "2021 TWD, purchaser price": "2021 TWD, purchaser price",
  "2021 USD, purchaser price": "2021 USD, purchaser price",
  Actions: "Actions",
  Active: "Active",
  "Activity Log": "Activity Log",
  "Activity Type": "Activity Type",
  "Actual Data": "Actual Data",
  Add: "Add",
  "Add an Image": "Add an Image",
  "Add Data for": "Add Data for {{name}}",
  "Add Data for Emission Removal and Mitigation Activities":
    "Add Data for Emission Removal and Mitigation Activities",
  "Add Data for Scope 0": "Add Data for Scope 0",
  "Add Data for Scope 2": "Add Data for Scope 2",
  "Add Emission Factor": "Add Emission Factor",
  "Add New Asset": "Add New Asset",
  "Add New Emission": "Add New Emission",
  "Add New Framework": "Add New Framework",
  Afghanistan: "Afghanistan",
  Air: "Air",
  "Air Travel - Long Haul (>= 2300 miles)":
    "Air Travel - Long Haul (>= 2300 miles)",
  "Air Travel - Medium Haul (>= 300 miles, < 2300 miles)":
    "Air Travel - Medium Haul (>= 300 miles, < 2300 miles)",
  "Air Travel - Short Haul (< 300 miles)":
    "Air Travel - Short Haul (< 300 miles)",
  Albania: "Albania",
  "Alert!": "Alert!",
  Algeria: "Algeria",
  "All frameworks have already been added":
    "All frameworks have already been added",
  Andorra: "Andorra",
  Angola: "Angola",
  Anguilla: "Anguilla",
  "Antigua and Barbuda": "Antigua and Barbuda",
  "Are you sure want to delete": "Are you sure you want to delete",
  Argentina: "Argentina",
  Armenia: "Armenia",
  Aruba: "Aruba",
  Australia: "Australia",
  Austria: "Austria",
  Azerbaijan: "Azerbaijan",
  Back: "Back",
  Bahamas: "Bahamas",
  Bahrain: "Bahrain",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  "Base Unit": "Base Unit",
  bbl: "bbl",
  "bbl crude": "bbl crude",
  Belarus: "Belarus",
  Belgium: "Belgium",
  Belize: "Belize",
  Benin: "Benin",
  Bermuda: "Bermuda",
  Bhutan: "Bhutan",
  Bolivia: "Bolivia",
  "Bosnia and Herzegovina": "Bosnia and Herzegovina",
  Botswana: "Botswana",
  Brand: "Brand",
  Brazil: "Brazil",
  "British Indian Ocean Territory": "British Indian Ocean Territory",
  "Browse your files": "Browse your files",
  Brunei: "Brunei",
  Btu: "Btu",
  Bug: "Bug",
  Building: "Building",
  "Building Type": "Building Type",
  Bulgaria: "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  Burundi: "Burundi",
  Bus: "Bus",
  "Business Travel": "Business Travel",
  "Calculate Method": "Calculate Method",
  "Calculate Type": "Calculate Type",
  "Calculated Method": "Calculated Method",
  "Calculation Approach": "Calculation Approach",
  "Call For Help": "Call For Help",
  Cambodia: "Cambodia",
  Cameroon: "Cameroon",
  Canada: "Canada",
  Cancel: "Cancel",
  "Cape Verde": "Cape Verde",
  Car: "Car",
  "Carbon Finance": "Carbon Finance123",
  "Carbon Neutral Planning": "Carbon Neutral Planning",
  Category: "Category",
  "Category Name": "Category Name",
  "Cayman Islands": "Cayman Islands",
  ccf: "ccf",
  "Central African Republic": "Central African Republic",
  "CH₄ Factor Value": "CH₄ Factor Value",
  "CH₄ Unit": "CH₄ Unit",
  Chad: "Chad",
  "Change Password": "Change Password",
  Chile: "Chile",
  China: "China",
  "Choose a file": "Choose a file",
  "Christmas Island": "Christmas Island",
  Close: "Close",
  "CO₂ Factor Value": "CO₂ Factor Value",
  "CO₂e (tonne)": "CO₂e (tonne)",
  "Cocos (Keelig) Islands": "Cocos (Keelig) Islands",
  Colombia: "Colombia",
  "Commissioned Date": "Commissioned Date",
  "Commuter Rail D": "Commuter Rail D",
  Comoros: "Comoros",
  completion: "completion",
  Compliment: "Compliment",
  compressor: "compressor",
  "Confirm Delete": "Confirm Delete",
  Congo: "Congo",
  "Convert Emission": "Convert Emission",
  "Cook Islands": "Cook Islands",
  "Costa Rica": "Costa Rica",
  Create: "Create",
  Croatia: "Croatia",
  Cuba: "Cuba",
  "Custom emission factor": "Custom emission factor",
  "Custom Emission Factor": "Custom Emission Factor",
  "Custom Emission Factor List": "Custom Emission Factor List",
  "Custom Emission Factor Name": "Custom Emission Factor Name",
  "Customer Feedback Form": "Customer Feedback Form",
  "Customer Feedback List": "Customer Feedback List",
  Cyprus: "Cyprus",
  "Czech Republic": "Czech Republic",
  Dashboard: "Dashboard",
  "Data Validation": "Data Validation",
  "Data Validation File": "Data Validation File",
  Delete: "Delete",
  "Delete Framework": "Delete Framework",
  Denmark: "Denmark",
  "Description of the uploaded file": "File Description",
  "Details View": "Details View",
  Distance: "Distance",
  Djibouti: "Djibouti",
  "Do you have any suggestions to improve our product and service?":
    "Do you have any suggestions to improve our product and service?",
  "Do you want to keep your changes ?": "Do you want to keep your changes ?",
  Dominica: "Dominica",
  "Dominican Republic": "Dominican Republic",
  Download: "Download",
  Ecuador: "Ecuador",
  Edit: "Edit",
  "Edit Data for": "Edit Data for {{name}}",
  "Edit Data for Emission Removal and Mitigation Activities":
    "Edit Data for Emission Removal and Mitigation Activities",
  "Edit Mode": "Edit Mode",
  Egypt: "Egypt",
  "El Salvador": "El Salvador",
  Email: "Email",
  "Email can't be empty!": "Email can't be empty!",
  "Email or password does not match!": "Email or password does not match!",
  "Emission Factor": "Emission Factor",
  "Emission Factor Classification": "Emission Factor Classification",
  "Emission Factor Management": "Emission Factor Management",
  "Emission Factor Name": "Emission Factor Name",
  "Emission Unit": "Emission Unit",
  "Employee Commute": "Employee Commute",
  "End Date": "End Date",
  "Energy Source": "Energy Source",
  "Energy Usage": "Energy Usage",
  "Equatorial Guinea": "Equatorial Guinea",
  Equipment: "Equipment",
  Eritrea: "Eritrea",
  Estonia: "Estonia",
  Ethiopia: "Ethiopia",
  Excel: "Excel",
  "Excel Download": "Excel Download",
  "Excel export & import": "Excel export & import",
  "External Emission": "External Emission",
  "Facility Company": "Facility Company",
  "Falkland Islands": "Falkland Islands",
  "Faroe Islands": "Faroe Islands",
  Ferry: "Ferry",
  Fiji: "Fiji",
  "Fill Company Name!": "Fill Company Name!",
  "Fill Custom Emission Factor Name!": "Fill Custom Emission Factor Name!",
  "Fill Email!": "Fill Email!",
  "Fill Emission Value!": "Fill Emission Value!",
  "Fill Password!": "Fill Password!",
  "Fill Site Name!": "Fill Site Name!",
  "Fill Source of Emission!": "Fill Source of Emission!",
  "Fill User Name!": "Fill User Name!",
  Finland: "Finland",
  "Fire Extinguisher": "Fire Extinguisher",
  framework: "framework",
  France: "France",
  "French Polynesia": "French Polynesia",
  "Fuel Consumption": "Fuel Consumption",
  "Fuel Type": "Fuel Type",
  "Fuel Used": "Fuel Used",
  g: "g",
  Gabon: "Gabon",
  "gal (US)": "gal (US)",
  Gambia: "Gambia",
  "gCH₄": "gCH₄",
  "gCO₂": "gCO₂",
  "gCO₂e": "gCO₂e",
  Georgia: "Georgia",
  Germany: "Germany",
  "GgCH₄": "GgCH₄",
  "GgCO₂": "GgCO₂",
  "GgN₂O": "GgN₂O",
  Ghana: "Ghana",
  Gibraltar: "Gibraltar",
  GJ: "GJ",
  "gN₂O": "gN₂O",
  Greece: "Greece",
  Greenland: "Greenland",
  Grenada: "Grenada",
  "Grid Average / Location Based": "Grid Average / Location Based",
  "Grid Average/ Location Based": "Grid Average/ Location Based",
  "Grid Average/Location Based": "Grid Average/Location Based",
  Guadeloupe: "Guadeloupe",
  Guam: "Guam",
  Guatemala: "Guatemala",
  Guernsey: "Guernsey",
  Guinea: "Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  Guyana: "Guyana",
  GWh: "GWh",
  ha: "ha",
  "ha/year": "ha/year",
  "ha/yr": "ha/yr",
  Haiti: "Haiti",
  "head/yr": "head/yr",
  "Heard Island and McDonald Islands": "Heard Island and McDonald Islands",
  "Heat/Steam": "Heat/Steam",
  Honduras: "Honduras",
  "Hong Kong": "Hong Kong",
  Hphr: "Hphr",
  Hungary: "Hungary",
  Iceland: "Iceland",
  Image: "Image",
  Incineration: "Incineration",
  India: "India",
  Indonesia: "Indonesia",
  "Intercity Rail (i.e. Amtrak) C": "Intercity Rail (i.e. Amtrak) C",
  "Invalid email address!": "Invalid email address!",
  Iran: "Iran",
  Iraq: "Iraq",
  Ireland: "Ireland",
  "Isle of Man": "Isle of Man",
  Israel: "Israel",
  Italy: "Italy",
  "Ivory Coast": "Ivory Coast",
  Jamaica: "Jamaica",
  Japan: "Japan",
  Jersey: "Jersey",
  Jordan: "Jordan",
  Kazakhstan: "Kazakhstan",
  Kenya: "Kenya",
  kg: "kg",
  "kgCH₄": "kgCH₄",
  "kgCO₂": "kgCO₂",
  "kgCO₂e": "kgCO₂e",
  "kgN₂O": "kgN₂O",
  Kiribati: "Kiribati",
  km: "km",
  Kosovo: "Kosovo",
  Kuwait: "Kuwait",
  kWh: "kWh",
  Kyrgyzstan: "Kyrgyzstan",
  "Land fill": "Land fill",
  Laos: "Laos",
  Latvia: "Latvia",
  lbs: "lbs",
  Lebanon: "Lebanon",
  Lesotho: "Lesotho",
  Liberia: "Liberia",
  Libya: "Libya",
  Liechtenstein: "Liechtenstein",
  "Light-Duty Truck B": "Light-Duty Truck B",
  Liter: "Liter",
  Lithuania: "Lithuania",
  "Location Based": "Location Based",
  "Log Out": "Log Out",
  Long: "Long",
  Luxembourg: "Luxembourg",
  m3: "m3",
  Macau: "Macau",
  Macedonia: "Macedonia",
  Madagascar: "Madagascar",
  Malawi: "Malawi",
  Malaysia: "Malaysia",
  Maldives: "Maldives",
  Mali: "Mali",
  Malta: "Malta",
  "Manage Users": "Manage Users",
  Manual: "Manual",
  "Manual Entry": "Manual Entry",
  "Marshall Islands": "Marshall Islands",
  Martinique: "Martinique",
  Mauritania: "Mauritania",
  Mauritius: "Mauritius",
  Mayotte: "Mayotte",
  "Mcf gas flared": "Mcf gas flared",
  "McfCH₄": "McfCH₄",
  "McfCO₂": "McfCO₂",
  "McfN₂O": "McfN₂O",
  Medium: "Medium",
  "Method of Travel": "Method of Travel",
  "Metric Tons CH₄": "Metric Tons CH₄",
  "Metric Tons CO₂": "Metric Tons CO₂",
  "Metric Tons CO₂e": "Metric Tons CO₂e",
  "Metric Tons N₂O": "Metric Tons N₂O",
  Mexico: "Mexico",
  mᵌ: "mᵌ",
  mile: "mile",
  MJ: "MJ",
  mmBtu: "mmBtu",
  "MMcf gas processed": "MMcf gas processed",
  "MMcf gas to flare": "MMcf gas to flare",
  "Mobile Combustion": "Mobile Combustion",
  "Mode of transport": "Mode of transport",
  Moldova: "Moldova",
  Monaco: "Monaco",
  Mongolia: "Mongolia",
  Montenegro: "Montenegro",
  Monthly: "Monthly",
  Montserrat: "Montserrat",
  "More Info": "More Info",
  Morocco: "Morocco",
  Motorcycle: "Motorcycle",
  Mozambique: "Mozambique",
  MWh: "MWh",
  "My Dashboard": "My Dashboard",
  "My Emission Inventory": "My Emission Inventory",
  Myanmar: "Myanmar",
  "N₂O Factor Value": "N₂O Factor Value",
  "N₂O Unit": "N₂O Unit",
  Name: "Name",
  Namibia: "Namibia",
  Nauru: "Nauru",
  "nautical mile": "nautical mile",
  Nepal: "Nepal",
  Netherlands: "Netherlands",
  "New Caledonia": "New Caledonia",
  "New Zealand": "New Zealand",
  Nicaragua: "Nicaragua",
  Niger: "Niger",
  Nigeria: "Nigeria",
  Niue: "Niue",
  No: "No",
  "No File Chosen": "No File Chosen",
  "No File Selected": "No File Selected.",
  "Norfolk Island": "Norfolk Island",
  "Normal View": "Normal View",
  "North Korea": "North Korea",
  "Northern Mariana Islands": "Northern Mariana Islands",
  Norway: "Norway",
  "Not Allow Special Characters!": "Not Allow Special Characters!",
  OK: "OK",
  Oman: "Oman",
  "On-Boarding Information": "On-Boarding Information",
  Other: "Other",
  Pakistan: "Pakistan",
  Palau: "Palau",
  Panama: "Panama",
  "Papua New Guinea": "Papua New Guinea",
  Paraguay: "Paraguay",
  "Passenger Car A": "Passenger Car A",
  "Passenger Distance": "Passenger Distance",
  "passenger-daily": "passenger-daily",
  "passenger-hour": "passenger-hour",
  "passenger-km": "passenger-km",
  "passenger-mile": "passenger-mile",
  "passenger-year": "passenger-year",
  Password: "Password",
  "Password can't be empty!": "Password can't be empty!",
  "Password must be minium 8 Characters":
    "Password must be minium 8 Characters",
  "Password must include Minimum eight characters, at least one letter, one number and one special character":
    "Password must include Minimum eight characters, at least one letter, one number and one special character",
  "per FTE Working Hour": "per FTE Working Hour",
  Peru: "Peru",
  Philippines: "Philippines",
  Pitcairn: "Pitcairn",
  "Please contact the system administrator to create the login account.":
    "Please contact the system administrator to create the login account.",
  "Please enter KPI.": "Please enter KPI.",
  "Please enter Objectives.": "Please enter Objectives.",
  "Please enter Sub-Pillar Owner Name.": "Please enter Sub-Pillar Owner Name.",
  "Please enter Sub-Pillar Owner Title.":
    "Please enter Sub-Pillar Owner Title.",
  "Please fill Calculate Method!": "Please fill Calculate Method!",
  "Please fill Email!": "Please fill Email!",
  "Please fill Emission Source!": "Please fill Emission Source!",
  "Please fill Equipment Category!": "Please fill Equipment Category!",
  "Please fill equipment name!": "Please fill equipment name!",
  "Please fill Equipment Name!": "Please fill Equipment Name!",
  "Please fill Euipment Type!": "Please fill Euipment Type!",
  "Please fill fuel type!": "Please fill fuel type!",
  "Please fill Fuel Type!": "Please fill Fuel Type!",
  "Please fill Method of Calculation!": "Please fill Method of Calculation!",
  "Please fill Name!": "Please fill Name!",
  "Please fill Password!": "Please fill Password!",
  "Please fill Refrigerants Used!": "Please fill Refrigerants Used!",
  "Please fill Source!": "Please fill Source!",
  "Please fill supplier name!": "Please fill supplier name!",
  "Please fill Supplier Name!": "Please fill Supplier Name!",
  "Please fill Transportation Name!": "Please fill Transportation Name!",
  "Please fill unit!": "Please fill unit!",
  "Please fill Unit!": "Please fill Unit!",
  "Please fill User Name!": "Please fill User Name!",
  "Please fill waste management vendor name!":
    "Please fill waste management vendor name!",
  "Please select activity type!": "Please select activity type!",
  "Please select Activity Type!": "Please select Activity Type!",
  "Please select Base Year.": "Please select Base Year.",
  "Please select Calculated Method!": "Please select Calculated Method!",
  "Please select Calculation Approach!": "Please select Calculation Approach!",
  "Please select data source!": "Please select data source!",
  "Please select Emission Factor!": "Please select Emission Factor!",
  "Please select Emission Source!": "Please select Emission Source!",
  "Please select Emission Type!": "Please select Emission Type!",
  "Please select Energy Type!": "Please select Energy Type!",
  "Please select Frequency of Measurement.":
    "Please select Frequency of Measurement.",
  "Please select Key Dependencies": "Please select Key Dependencies",
  "Please select KPI Owner Name.": "Please select KPI Owner Name.",
  "Please select KPI Owner Title.": "Please select KPI Owner Title.",
  "Please select method of calculation!":
    "Please select method of calculation!",
  "Please select Method of Calculation!":
    "Please select Method of Calculation!",
  "Please select one of activity type!": "Please select one of activity type!",
  "Please select one of building type!.":
    "Please select one of building type!.",
  "Please select one of calculation approach!":
    "Please select one of calculation approach!",
  "Please select one of category!": "Please select one of category!",
  "Please select one of energy source!": "Please select one of energy source!",
  "Please select one of ESG Pillar.": "Please select one of ESG Pillar.",
  "Please select one of ESG Sub-Pillar.":
    "Please select one of ESG Sub-Pillar.",
  "Please select one of the rapid assessment framework!":
    "Please select one of the rapid assessment framework!",
  "Please select one of Vehicle Type!": "Please select one of Vehicle Type!",
  "Please select Purchased Good!": "Please select Purchased Good!",
  "Please select Source Type!": "Please select Source Type!",
  "Please select Source!": "Please select Source!",
  "Please select Standards Alignment.": "Please select Standards Alignment.",
  "Please select Transport Mode!": "Please select Transport Mode!",
  "Please select transportation name!": "Please select transportation name!",
  "Please select Unit of Measurement.": "Please select Unit of Measurement.",
  "Please select vehicle type!": "Please select vehicle type!",
  "Please select Vehicle Type!": "Please select Vehicle Type!",
  "Please select waste treatment method!":
    "Please select waste treatment method!",
  Poland: "Poland",
  Portfolios: "Portfolios",
  Portugal: "Portugal",
  "Preview File": "Preview File",
  "Project Type": "Project Type",
  "Puerto Rico": "Puerto Rico",
  pump: "pump",
  "Purchased Electricity": "Purchased Electricity",
  "Purchased Electricity - Location Based":
    "Purchased Electricity - Location Based",
  "Purchased Electricity - Market Based":
    "Purchased Electricity - Market Based",
  "Purchased Electricity(Location Based)":
    "Purchased Electricity(Location Based)",
  "Purchased Heat and Steam": "Purchased Heat and Steam",
  Qatar: "Qatar",
  Quarterly: "Quarterly",
  Rail: "Rail",
  "range of total": "{{range}} of {{total}}",
  "Reason for selecting the uploaded file":
    "Reason for selecting the uploaded file",
  "Record Period": "Record Period",
  Recycling: "Recycling",
  "Refrigerants and Fugitives": "Refrigerants and Fugitives",
  "Report Generation": "Report Generation",
  Reset: "Reset",
  Réunion: "Réunion",
  "rig engine": "rig engine",
  Role: "Role",
  Romania: "Romania",
  "Room per night": "Room per night",
  Russia: "Russia",
  Rwanda: "Rwanda",
  "Saint Kitts and Nevis": "Saint Kitts and Nevis",
  "Saint Lucia": "Saint Lucia",
  "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
  Samoa: "Samoa",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "Sao Tome and Principe",
  "Saudi Arabia": "Saudi Arabia",
  Save: "Save",
  "Save Progress": "Save Progress",
  scf: "scf",
  "scfCH₄": "scfCH₄",
  "scfCO₂": "scfCO₂",
  "scfdCH₄": "scfdCH₄",
  "scfdCO₂": "scfdCO₂",
  "scfdN₂O": "scfdN₂O",
  "scfN₂O": "scfN₂O",
  Scope: "Scope",
  "Scope Category": "Scope Category",
  Search: "Search",
  "Search Company": "Search Company",
  Search_: "Search...",
  "See More": "See More",
  "Select a Type": "Select a Type",
  "Select All Categories": "Select All Categories",
  "Select Calculate Method": "Select Calculate Method",
  "Select Calculation Approach": "Select Calculation Approach",
  "Select Category": "Select Category",
  "Select Country": "Select Country",
  "Select Emission Factor": "Select Emission Factor",
  "Select Emission Factor Name": "Select Emission Factor Name",
  "Select Emission Factor Source": "Select Emission Factor Source",
  "Select Emission Type 1": "Select Emission Type 1",
  "Select Emission Unit": "Select Emission Unit",
  "Select Energy Source": "Select Energy Source",
  "Select Equipment Category": "Select Equipment Category",
  "Select Material": "Select Material",
  "Select Materiality Topic": "Select Materiality Topic",
  "Select Project Type": "Select Project Type",
  "Select Record Period": "Select Record Period",
  "Select Role": "Select Role",
  "Select Scope": "Select Scope",
  "Select source": "Select source",
  "Select Source Type": "Select Source Type",
  "Select Unit": "Select Unit",
  "Select Year": "Select Year",
  Select_: "Select...",
  Senegal: "Senegal",
  Serbia: "Serbia",
  Setup: "Setup",
  Seychelles: "Seychelles",
  Short: "Short",
  "short tons": "short tons",
  "Sierra Leone": "Sierra Leone",
  Singapore: "Singapore",
  Site: "Site",
  "Site Logo": "Site Logo",
  "Site Name": "Site Name",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  Solidified: "Solidified",
  "Solomon Islands": "Solomon Islands",
  Somalia: "Somalia",
  "South Africa": "South Africa",
  "South Georgia and the South Sandwich Islands":
    "South Georgia and the South Sandwich Islands",
  "South Korea": "South Korea",
  Spain: "Spain",
  "Sr. no.": "Sr. no.",
  "Sri Lanka": "Sri Lanka",
  "Start Date": "Start Date",
  "Stationary Combustion": "Stationary Combustion",
  "Steam and Heat": "Steam and Heat",
  "Subsidiary Company": "Subsidiary Company",
  Sudan: "Sudan",
  Suggestion: "Suggestion",
  Supplier: "Supplier",
  "Supplier Name": "Supplier Name",
  "Supplier-specific method": "Supplier-specific method",
  Suriname: "Suriname",
  Swaziland: "Swaziland",
  Sweden: "Sweden",
  Switzerland: "Switzerland",
  Syria: "Syria",
  Taiwan: "Taiwan",
  "Taiwan CFP": "Taiwan CFP",
  Tanzania: "Tanzania",
  "tCO₂": "tCO₂",
  Thailand: "Thailand",
  "There is no data.": "There is no data.",
  therm: "therm",
  "Timor-Leste": "Timor-Leste",
  Togo: "Togo",
  Tokelau: "Tokelau",
  "ton-mile": "ton-mile",
  Tonga: "Tonga",
  tonne: "tonne",
  "tonne air-dry peat": "tonne air-dry peat",
  "tonne dry matter": "tonne dry matter",
  "tonne-km": "tonne-km",
  "tonneCH₄": "tonneCH₄",
  "tonneCO₂": "tonneCO₂",
  "tonneN₂O": "tonneN₂O",
  "Total Log": "Total Log",
  "Transit Rail (i.e. Subway, Tram) E": "Transit Rail (i.e. Subway, Tram) E",
  "Trinidad and Tobago": "Trinidad and Tobago",
  Tunisia: "Tunisia",
  Turkey: "Turkey",
  Turkmenisten: "Turkmenisten",
  "Turks and Caicos Islands": "Turks and Caicos Islands",
  Type: "Type",
  "Type of Feedback": "Type of Feedback",
  Uganda: "Uganda",
  "UK DEFRA": "UK DEFRA",
  Ukraine: "Ukraine",
  Unit: "Unit",
  "Unit of Fuel": "Unit of Fuel",
  "Unit or Floor": "Unit/Floor",
  "United Arab Emirates": "United Arab Emirates",
  "United Kingdom": "United Kingdom",
  Update: "Update",
  "Upload file": "Upload file",
  upload_new: "Upload New",
  uploaded_file_description: "Uploaded File Description",
  "Upstream T&D": "Upstream T&D",
  Uruguay: "Uruguay",
  "US EPA": "US EPA",
  USA: "USA",
  Usage: "Usage",
  User: "User",
  "User Management": "User Management",
  "User Name": "User Name",
  Uzbekistan: "Uzbekistan",
  Vanuatu: "Vanuatu",
  "Vatican City State (Holy See)": "Vatican City State (Holy See)",
  Vehicle: "Vehicle",
  "Vehicle Distance": "Vehicle Distance",
  "Vehicle Type": "Vehicle Type",
  "vehicle-km": "vehicle-km",
  "vehicle-mile": "vehicle-mile",
  Venezuela: "Venezuela",
  "Verification Customer View": "Verification Customer View",
  Vietnam: "Vietnam",
  "Wallis and Futuna": "Wallis and Futuna",
  "Waste-type specific method": "Waste-type specific method",
  "Weight Distance": "Weight Distance",
  well: "well",
  workover: "workover",
  "Write your suggestion": "Write your suggestion",
  Year: "Year",
  "year-compressor": "year-compressor",
  Yearly: "Yearly",
  Yemen: "Yemen",
  Yes: "Yes",
  "You have answered this amount of questions in":
    "You have answered this amount of questions in",
  "You've successfully sent a request to the Customer Service Team":
    "You've successfully sent a request to the Customer Service Team",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabwe",
  "Tainan Science Park of STSP(Land fill)":
    "Tainan Science Park of STSP(Land fill)",
  "Gangshan refuse incineration plant": "Gangshan refuse incineration plant",
  "Miaoli refuse incineration plant": "Miaoli refuse incineration plant",
  "Yong kang, Tainan waste recycling plant":
    "Yong kang, Tainan waste recycling plant",
  "Tainan refuse incineration plant": "Tainan refuse incineration plant",
  "Tainan Science Park of STSP(Incineration)":
    "Tainan Science Park of STSP(Incineration)",
  "Recycling and reuse": "Recycling and reuse",
  "Tainan Science Park of STSP(Solidified)":
    "Tainan Science Park of STSP(Solidified)",
  Complete: "Complete",
  "Consolidated Report": "Consolidated Report",
  "Do you want to complete this report?":
    "Do you want to complete this report?",
  "Are you sure you want to delete?": "Are you sure you want to delete?",
  "Release Notes": "Release Notes",
  "No Data Found!": "No Data Found!",
};

module.exports = {dummy}
